### ISSUE TITLE
&&

### ISSUE THREAD

**Issue by miyendisa** [doganseyfisen/Artik-Yil-Bulma-Programi#1]
Merhabalar,
if (year%4==0 && year%400==0){} ifadesinde && operatörüyle istenen koşul sağlanmıyor.  Girilen yılın artık olabilmesi için bu ifadeye ve kodunuzun devamına göre yılın hem 4 ile hem de 400 ile bölünmesi gerekiyor. Ancak örneğin 2024 yılı da bir artık yıldır.

**Comment by doganseyfisen** [comment]
İncelemeniz ve düzeltmeniz için teşekkürler, şu an bilgisayar başında değilim. Sabah mutlaka bakacağım.

**Comment by miyendisa** [comment]
Rica ederim. Kolaylıklar dilerim.
